os: osx
osx_image: xcode10.2
language: objective-c
sudo: false
env:
  global:
  - THEOS=~/theos
before_install:
  - brew update
  - brew install dpkg ldid
  - git clone --recursive git://github.com/theos/theos.git ~/theos
script:
  - "export VERSION=$(grep 'Version: ' control | sed 's/^.*: //')"
  - "export DESCRIPTION=$(awk '/## v$VERSION/{getline; print}' README.md)"
  - "export FILENAME='packages/'\"$(grep 'Package: ' control | sed 's/^.*: //')\"'_'\"$VERSION\"'_iphoneos-arm.deb'"
  - make package
before_deploy:
  - git config --local user.name "Jeff Rescignano"
  - git config --local user.email "jeff@jeffresc.dev"
  - if [ "$TRAVIS_BRANCH" == "release" ]; then git tag -a v$VERSION -m "$DESCRIPTION"; fi
deploy:
  provider: releases
  api_key:
    secure: L4NQAHrKpZXwQQArupo3bfEpZTfgUoNVTmNnKdWV0S4lt+vHHWmVigeFx+FvdaFr3H8B6heLIAv25boFPVEbBf+KYoLcMpxLzpvEaMT3P57fdZL5E9CtZaY5zX4AO1UBJlIdQg7O8maUB1vygEKmk+9ckhfkhYHfs86oSR5lVvCu6RDFzmnUj/YZMYRkTSzkrx2XkWQ7Q8OeLfpGxqzJfVytbnGEWn9uAoBpwjM3PabaHC+8QuhoZpVdlsZiaeCAHdF+uS4r15pBqTFmeDArEgf7HxzC88/V8+PSKQGOqWFe66CjhSNglDr57cUoAF1qC/VzlVvrXsIPhQiEoWLIJowfNMID4VM3tKPN736GP7cVa3eDmo6r13XRjuSNbbIJEV4hxmzqCSyPSndwmAxb/Qw4G1vD+RnZ8auR2Qh2MvDt9KFe9dOGnbTHmNUWttc65pNY/I500QlzdEKjtzIgKGe021OC47O/dF7qLP4JbvboROm6IVNqAedSNZeRPg66GP8/s6wtr6/nXgXFp7SBJ6giSdyL4nyPwSgn0HUjgRZ9dxVmeaYRnOqWyMeBnd+aVQP7Pg/m/84RvlUyfJjwKEaMMxIagjU+kKTQCOhG2DQqFA/LMqtKMaHMlLBIVJvYC7mc669uUUiuU7eNkn204g5L5oNdrbwc1Zwvl+wfxSY=
  file: $FILENAME
  skip_cleanup: true
  on:
    branches:
      only:
        - release
branches:
  except:
  - /^untagged/
